export default {
  code: `for n in range(1,5):
  print(n)`,
  steps: [
    {
      lineNumber: 0,
      explanation: "<p>In this tutorial, we'll learn about the <code>range()</code> function, which is commonly used with <code>for</code> loops.</p><p>The <code>range(1, 5)</code> function generates a sequence of numbers starting from 1 up to (but not including) 5. So it produces: 1, 2, 3, 4.</p>",
      highlightLines: [],
      boxes: [
        {
          title: "Memory",
          values: {}
        },
        {
          title: "Output",
          values: []
        }
      ]
    },
    {
      lineNumber: 0,
      explanation: "<p>The <code>for</code> loop will iterate through each number generated by <code>range(1, 5)</code>.</p><p>First iteration: <code>n</code> is assigned <code>1</code>.</p>",
      highlightLines: [0],
      boxes: [
        {
          title: "Memory",
          values: {}
        },
        {
          title: "Output",
          values: []
        }
      ]
    },
    {
      lineNumber: 1,
      explanation: "<p>Print the value of <code>n</code>, which is <code>1</code>.</p>",
      highlightLines: [1],
      boxes: [
        {
          title: "Memory",
          values: { "n": { value: 1, highlight: true } },
          connections: [
            { from: "n", toValue: "1" }
          ]
        },
        {
          title: "Output",
          values: []
        }
      ]
    },
    {
      lineNumber: 0,
      explanation: "<p>The loop moves to the next number in the range.</p><p>Second iteration: <code>n</code> is assigned <code>2</code>.</p>",
      highlightLines: [0],
      boxes: [
        {
          title: "Memory",
          values: { "n": 1 },
          connections: [
            { from: "n", toValue: "1" }
          ]
        },
        {
          title: "Output",
          values: [1]
        }
      ]
    },
    {
      lineNumber: 1,
      explanation: "<p>Print the value of <code>n</code>, which is now <code>2</code>.</p>",
      highlightLines: [1],
      boxes: [
        {
          title: "Memory",
          values: { "n": { value: 2, highlight: true } },
          connections: [
            { from: "n", toValue: "2" }
          ]
        },
        {
          title: "Output",
          values: [1]
        }
      ]
    },
    {
      lineNumber: 0,
      explanation: "<p>The loop moves to the next number in the range.</p><p>Third iteration: <code>n</code> is assigned <code>3</code>.</p>",
      highlightLines: [0],
      boxes: [
        {
          title: "Memory",
          values: { "n": 2 },
          connections: [
            { from: "n", toValue: "2" }
          ]
        },
        {
          title: "Output",
          values: [1, 2]
        }
      ]
    },
    {
      lineNumber: 1,
      explanation: "<p>Print the value of <code>n</code>, which is now <code>3</code>.</p>",
      highlightLines: [1],
      boxes: [
        {
          title: "Memory",
          values: { "n": { value: 3, highlight: true } },
          connections: [
            { from: "n", toValue: "3" }
          ]
        },
        {
          title: "Output",
          values: [1, 2]
        }
      ]
    },
    {
      lineNumber: 0,
      explanation: "<p>The loop moves to the next number in the range.</p><p>Fourth iteration: <code>n</code> is assigned <code>4</code>.</p>",
      highlightLines: [0],
      boxes: [
        {
          title: "Memory",
          values: { "n": 3 },
          connections: [
            { from: "n", toValue: "3" }
          ]
        },
        {
          title: "Output",
          values: [1, 2, 3]
        }
      ]
    },
    {
      lineNumber: 1,
      explanation: "<p>Print the value of <code>n</code>, which is now <code>4</code>.</p>",
      highlightLines: [1],
      boxes: [
        {
          title: "Memory",
          values: { "n": { value: 4, highlight: true } },
          connections: [
            { from: "n", toValue: "4" }
          ]
        },
        {
          title: "Output",
          values: [1, 2, 3]
        }
      ]
    },
    {
      lineNumber: 1,
      explanation: "<p>The range has been exhausted—there are no more numbers to iterate through. The loop ends.</p><p><strong>Important:</strong> <code>range(1, 5)</code> generates numbers from 1 up to (but <em>not including</em>) 5. So it produces 1, 2, 3, 4—not 5!</p>",
      boxes: [
        {
          title: "Memory",
          values: { "n": 4 },
          connections: [
            { from: "n", toValue: "4" }
          ]
        },
        {
          title: "Output",
          values: [1, 2, 3, 4]
        }
      ]
    }
  ]
};
